#!/bin/bash

export GENAI_API_KEY="ENTER_VALUE_HERE"
export OPENCTI_API_KEY="ENTER_VALUE_HERE"
export OPENCTI_INSTANCE="ENTER_VALUE_HERE"
export CYBERCRIMINAL_ORG="ENTER_VALUE_HERE"
export SCRAPING_FUNC="ENTER_VALUE_HERE"
